### ISSUE TITLE
strange result from the maze environment

### ISSUE THREAD

**Issue by JINKEHE** [openai/train-procgen#14]
perhaps I missed something, but why the first `eprewmean` in the `maze` environment is always `10.0`, which is already the highest score an agent can get?

**Comment by ganeshkumartk** [comment]
Hi @JINKEHE, I tried in virtual env but I couldn't reproduce the same, the score in ```maze``` was dynamic when I run for 3x . So, can you share your running logs if any, please

**Comment by JINKEHE** [comment]
Hi @CoDeRgAnEsh, thanks for your response. I don't have my running logs now but this error has already been reported in the results in this repository, for example, https://github.com/openai/train-procgen/blob/master/train_procgen/results/easy-200-run0/progress-maze-train.csv and https://github.com/openai/train-procgen/blob/master/train_procgen/results/easy-200-run0/progress-maze-test.csv. You can see that the eprewmean reported there always starts from 10.0, which is weird.

**Comment by kcobbe** [comment]
The episodes logs are initially biased (for perhaps the first 1-2 rollouts) towards short episodes, since only short episodes have had time to finish and log. This bias quickly vanishes. However, in maze, this means that the logs initially show an artificially high eprewmean, since all short episodes in maze have a high reward. The only way to terminate the episode before timeout is to successfully complete it.
